# Generated by Django 4.1.2 on 2022-10-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "username",
                    models.CharField(
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Pen Name",
                    ),
                ),
                ("EMAIL", models.EmailField(max_length=127, verbose_name="Email")),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "public_visibility",
                    models.BooleanField(verbose_name="Public Visibility"),
                ),
                ("dob", models.DateField(verbose_name="Date of Birth")),
                ("age", models.IntegerField(verbose_name="Age")),
                (
                    "account_type",
                    models.CharField(
                        choices=[("Author", "Author"), ("Seller", "Seller")],
                        max_length=10,
                        verbose_name="Account Type",
                    ),
                ),
                ("address", models.TextField(max_length=1000, verbose_name="Address")),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, verbose_name="Last Login"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date Joined"),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "about",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="about"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
