# Generated by Django 4.1.2 on 2022-10-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_book_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdetails", old_name="EMAIL", new_name="email",
        ),
    ]
