# Generated by Django 4.1.2 on 2022-10-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_book_app", "0002_rename_email_userdetails_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="account_type",
            field=models.CharField(
                choices=[("Author", "Author"), ("Seller", "Seller")],
                max_length=10,
                null=True,
                verbose_name="Account Type",
            ),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="address",
            field=models.TextField(max_length=1000, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="age",
            field=models.IntegerField(null=True, verbose_name="Age"),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="dob",
            field=models.DateField(null=True, verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="public_visibility",
            field=models.BooleanField(default=False, verbose_name="Public Visibility"),
        ),
    ]
