# Generated by Django 4.1.2 on 2022-10-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_book_app", "0003_alter_userdetails_account_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
