# Generated by Django 4.1.2 on 2022-10-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_book_app", "0004_alter_userdetails_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="last_login",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Last Login"
            ),
        ),
    ]
