# Generated by Django 4.1.2 on 2022-10-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_book_app", "0006_alter_userdetails_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="last_login",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Login"),
        ),
    ]
